### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by nadar** [signageos/cli#17]
When using `sos applet start` we constantly have the same problem:

1. it runs once
2. after next `sos applet start` (since there is no hot reload :cry: ....) we have the error messages `Not allowed to navigate to filesystem URL` or in Firefox `Unable to request PERSISTENT file system. Use TEMPORARY instead TypeError: r is undefined`

I was unable to find out what security flags in chrome (or ff) we can disabled to make applets run. 

Its almost impossible to develop applets. The docs are outdated. The guide about how to run things with vue (f.e) is not complete (how can we install hot reload?).

here you can find our example applet i am talking about: https://github.com/flyocloud/signageos-vue-example

**Comment by misak113** [comment]
Hi @nadar,
we have just released a new version of emulator @signageos/front-display@9.21.1
It should fix the "Chrome 104+" problem with applets. Can you please check it (upgrade dep above to the latest).

**Comment by nadar** [comment]
Seem the error is gone, but there must be another issue with caching of those files. also now we have

```
0946f6e0-ae35-4e0b-8219-6eb8d256836e:4 Uncaught (in promise) DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at blob:http://localhost:8090/0946f6e0-ae35-4e0b-8219-6eb8d256836e:4:748445
    at new Promise (<anonymous>)
    at e.exports (blob:http://localhost:8090/0946f6e0-ae35-4e0b-8219-6eb8d256836e:4:747903)
    at e.exports (blob:http://localhost:8090/0946f6e0-ae35-4e0b-8219-6eb8d256836e:4:763724)
    at a.request (blob:http://localhost:8090/0946f6e0-ae35-4e0b-8219-6eb8d256836e:4:762381)
    at a.<computed> [as get] (blob:http://localhost:8090/0946f6e0-ae35-4e0b-8219-6eb8d256836e:4:762687)
    at Function.get (blob:http://localhost:8090/0946f6e0-ae35-4e0b-8219-6eb8d256836e:4:746764)
    at blob:http://localhost:8090/0946f6e0-ae35-4e0b-8219-6eb8d256836e:4:752162
    at u (filesystem:http://localhost:8090/persistent/data/front-applet/5.2.0.js:8:262438)
    at Generator._invoke (filesystem:http://localhost:8090/persistent/data/front-applet/5.2.0.js:8:262226)
```

But the view is it least visible. But there must be also something with caching, filesystem caching... whatever.. it renders a completly different app we developed 1 year ago. Is there any sos applet cear filesystem cache option?

![image](https://user-images.githubusercontent.com/3417221/187900701-4c9cee20-9d76-471a-80c0-74d28cf03035.png)

**Comment by nadar** [comment]
My example code should just run a yellow hello world page :-) but rendering another applet

**Comment by nadar** [comment]
i also have to report with the latest example we never achieve `onReady` state... 

![image](https://user-images.githubusercontent.com/3417221/187907555-c7089ef8-aa91-48f1-a162-5e73eca67279.png)

How do other develop applets? :smile:
