### ISSUE TITLE
CI support in CLI

### ISSUE THREAD

**Issue by nickmeulen** [signageos/cli#24]
The cli fails to support usage in a CI/CD environment. The upload process fails when the upload begins despite succeeded all the validation steps. CI output:

```
Use applet project directory path: /<path_to_app>/signageos

Use applet entry file: /<path_to_app>/signageos/dist/index.html
Will create new version 0.1.2-release.8
undefined
spawn file ENOENT```

**Comment by misak113** [comment]
Hi, can you provide more information and details on the environment? What version of CLI are you using? How does the project look like? The content of `package.json` and other configuration files. What exactly the command for the upload applet looks like?
The problem can be related to missing some binary file (program) in your CI/CD pipeline machine/image.

**Comment by nickmeulen** [comment]
Resolved due to a missing dependency within the CI's docker image

**Comment by misak113** [comment]
For the record and potential problem-solving in the future. We are using [debug](https://www.npmjs.com/package/debug) package for logging. So this can be used to see detailed debug logs:
```sh
export DEBUG='@signageos/*'
```

For this specific issue for CircleCI was solved. The default docker image `cimg/node:16.18.1` has been missing the `file` program. The solution was to add the following lines to the CircleCI configuration file:

```yaml
- run: sudo apt-get update && sudo apt-get install -y file
```
