### ISSUE TITLE
sos.onReady() is never called

### ISSUE THREAD

**Issue by ps17092012** [signageos/cli#29]
Hello, I noticed that `sos.onReady()` is never called, even in a fresh applet created with `sos applet generate`. This is using the emulator. Using any other sos api calls also doesn't seem to work, maybe because it never gets ready.

CLI Version is 1.1.5

**Comment by misak113** [comment]
Hi, please, can you send me what port and host are you using for starting the emulator? It's a different port than the plain applet code itself.
And the applet has to run in the emulator environment. That's the current limitation of applets.

**Comment by ps17092012** [comment]
Thanks for the quick response!

Webpack is saying:
```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.2.32:8080/
<i> [webpack-dev-server] Content not from webpack is served from '[...]/public' directory
Emulator is running at http://192.168.2.32:8090
```

When going to the localhost:8080  or 192.168.2.32:8080, the page loads, but it never gets to the onReady() state. The last outputs are 
```
[webpack-dev-server] Server started: Hot Module Replacement enabled, Live Reloading enabled, Progress disabled, Overlay enabled.
[HMR] Waiting for update signal from WDS...
```

When going to 192.168.2.32:8090 (I'm not sure if that's supposed to work), there is an error in the console, both on firefox and chrome:
```
ReferenceError: caches is not defined
    _callee3$ serviceWorkerLoader.ts:29
    tryCatch runtime.js:65
    invoke runtime.js:303
    method runtime.js:117
    __awaiter bundle.js:198804
    __awaiter bundle.js:198786
    cacheAppFiles bundle.js:198874
    _callee$ serviceWorkerLoader.ts:9
    tryCatch runtime.js:65
    invoke runtime.js:303
    method runtime.js:117
    __awaiter bundle.js:198804
    __awaiter bundle.js:198786
    registerServiceWorker bundle.js:198814
    _callee$ bundle.tsx:19
    tryCatch runtime.js:65
    invoke runtime.js:303
    method runtime.js:117
    __awaiter bundle.js:205167
    __awaiter bundle.js:205149
    tsx bundle.tsx:18
    tsx bundle.tsx:72
```

**Comment by misak113** [comment]
Ok. I get it now. The problem is a new Web Browser feature used in emulator version 11+. The IndexedDB and Cache API that is available only in a secured context (https) and on localhost. It's totally removed when you run HTTP-only and outside the localhost (E.g.: http://192.168.2.32:8090). So you can just navigate to localhost instead of the local IP address and it should start working.
I'll manage the fix of URL in console log.

**Comment by misak113** [comment]
Duplicated issue https://github.com/signageos/cli/issues/28

**Comment by ps17092012** [comment]
so you're saying I should go to 0.0.0.0:8090?
In that case I'm getting a different error:
```
TypeError: storageInfo is undefined
    _callee39$/< ProprietaryFileSystem.ts:581
    _callee39$ ProprietaryFileSystem.ts:578
    tryCatch runtime.js:65
    invoke runtime.js:303
    method runtime.js:117
    __awaiter bundle.js:155214
    __awaiter bundle.js:155196
    requestFileSystem bundle.js:156775
    _callee$ ProprietaryFileSystem.ts:33
    tryCatch runtime.js:65
    invoke runtime.js:303
    method runtime.js:117
    rejected bundle.js:155206
    promise callback*step bundle.js:155212
    __awaiter bundle.js:155214
    __awaiter bundle.js:155196
    initialize bundle.js:155241
    _callee14$ DefaultDriver.ts:276
    tryCatch runtime.js:65
    invoke runtime.js:303
    method runtime.js:117
    fulfilled bundle.js:191457
    promise callback*step bundle.js:191470
    fulfilled bundle.js:191457
    promise callback*step bundle.js:191470
    __awaiter bundle.js:191472
    __awaiter bundle.js:191454
    initialize bundle.js:191852
    _callee$ bundle.tsx:27
    tryCatch runtime.js:65
    invoke runtime.js:303
    method runtime.js:117
    fulfilled bundle.js:205152
    promise callback*step bundle.js:205165
    __awaiter bundle.js:205167
    __awaiter bundle.js:205149
    tsx bundle.tsx:18
    tsx bundle.tsx:72
```

**Comment by misak113** [comment]
You can run URL: http://localhost:8090/

Or you can utilize the new featured fileSystem using the following URL: http://localhost:8090/?fileSystem=indexed_db (this is currently a private beta feature).

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/1695995/223396511-81424cb0-ccd9-4cc5-8df5-87c7f8bd2892.png">

**Comment by ps17092012** [comment]
Hm okay, http://localhost:8090/ is still not working (same error about the storageInfo as in my last comment, but with the indexed_db parameter it does work. 

I guess now that I know that, it is good enough for local testing. 
Thanks for your help!
